install.packages("raster")
remove.packages(c("rspatial"))
install.packages("rspatial")
install.packages("spdplyr")
install.packages("geojsonio")
install.packages("rmapshaper")
if (!require("rspatial")) devtools::install_github('rspatial/rspatial')
library(sp)
library(rspatial)
library(maptools)
library(dismo)
library(gstat)
library(raster)
library(rgdal)
library(spdplyr)
library(geojsonio)
library(rmapshaper)
setwd("D:/Mapping project/Data analyzing/Interpolation")
data<-read.csv2("./point_emo.csv",sep=",",dec=".")
data<-subset(data,emo_dis>0)
xy<-cbind(data$longitude,data$latitude)
dsp <- SpatialPoints(xy, proj4string=CRS("+init=epsg:5684"))
dsp <- SpatialPointsDataFrame(dsp, data)
Munich<-readShapePoly("./Munich/Munich.shp") 
proj4string(Munich) <- CRS("+init=epsg:5684")
v <- voronoi(dsp)
## Loading required namespace: deldir
v <- raster::intersect(v, Munich)
#spplot(v, 'valence',col.regions=rev(get_col_regions()))
r <- raster(Munich,ncol=100, nrow=100)
vr <- rasterize(v, r, 'emo_dis')
plot(vr)
gs <- gstat(formula=data$emo_dis~1, locations=dsp)
var <- variogram(gs)
plot(var)
fvs <- fit.variogram(var, vgm(0.7, "Sph", 0.02, 0.65))
plot(variogramLine(fvs, 0.15), type='l', ylim=c(0,1) ,col='blue', lwd=2)
points(var[,2:3], pch=20, col='red')
plot(var, fvs)
gs <- gstat(formula=data$emo_dis~1, locations=dsp)
idw <- interpolate(r, gs)
## [inverse distance weighted interpolation]
idwr <- mask(idw, vr)
plot(idwr)
poly_emo_vor<-rasterToPolygons(vr, fun=NULL, n=4, na.rm=TRUE)
poly_emo_100<-rasterToPolygons(idwr, fun=NULL, n=4, na.rm=TRUE)
colnames(poly_emo_100@data)<-c("score")
emo_vor_json <- geojson_json(poly_emo_vor)
emo_json_100 <- geojson_json(poly_emo_100)
cat(emo_json_100, file = (con <- file('emo_json_100.json', "w", encoding = "UTF-8")))
cat(emo_vor_json, file = (con <- file('emo_vor_json.json', "w", encoding = "UTF-8")))
close(con)
